### ISSUE TITLE
Tempfile

### ISSUE THREAD

**Issue by 007lva** [anykeyh/crystal-coverage#4]
Just a question. Why `require "tempfile"` was needed here?

https://github.com/anykeyh/crystal-coverage/commit/bd4db8260ce664d15c5c912fc3c0fbd95d30e090#diff-8d37261a58ddf04376fa214911114adc

**Comment by JadeKharats** [comment]
it is no longer useful. I am making a merge request.

**Comment by anykeyh** [comment]
Sorry for delay. I'm currently traveling in low-connection location. I've merged the PR! Thank you !
